project:
  type: website
  output-dir: docs
website:
  title: Troutman Lab
  navbar:
    background: dark
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: index.qmd
      - text: Publications
        href: index.qmd
      - text: Lab Members
        href: index.qmd
      - text: Analysis
        menu: 
          - text: "BMI Cluster"
            href: Pages/Analysis/BMI_Cluster.qmd
          - text: "Lab Cluster Drives"
            href: Pages/Analysis/Lab_Cluster_Drives.qmd
          - text: "Processing RNA-Seq Data"
            href: Pages/Analysis/processingRNASeqData.qmd
          - text: "Just beginning?"
            href: "https://github.com/ty-troutman/Genomics-analyses"
      - text: Sequencing
        menu:
          - text: "Database and Barcodes"
            href: Pages/Sequencing/Database_Barcodes.qmd
          - text: "Pooling and Submission"
            href: Pages/Sequencing/Pooling_Submission.qmd
          - text: "Downloading the Data"
            href: Pages/Sequencing/NGSScraper_KevinErnst.qmd
      - icon: github
        href: https://github.com/ty-troutman
        aria-label: Troutman GitHub
      - text: "CCHMC"
        href: "https://www.cincinnatichildrens.org/research/divisions/a/allergy-immunology/labs/troutman"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
editor: visual
