project:
  type: website
  output-dir: docs

website:
  title: Troutman Lab

  navbar:
    background: dark
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: qmd/Research.qmd
      - text: Publications
        href: qmd/Publications.qmd
      - text: Lab Members
        href: qmd/Lab_members.qmd
      - icon: github
        href: https://github.com/ty-troutman
        aria-label: Troutman GitHub
      - text: "Lab CCHMC website"
        href: "https://www.cincinnatichildrens.org/research/divisions/a/allergy-immunology/labs/troutman"

  sidebar:
    - id: internal-materials
      title: "Internal Materials"
      style: floating
      search: true
      collapse-level: 1
      contents:
        - qmd/internal/index.qmd

        - section: "Lab rules, policies, and expectations"
          contents:
            - qmd/internal/rules_policies.qmd

        - section: "Using the Server"
          contents:
            - qmd/internal/server_is4r_cluster.qmd
            - qmd/internal/server_lab_drives.qmd

        - section: "Sequencing Data"
          contents:
            - qmd/internal/processing_sequencing_data.qmd
            - qmd/internal/analysis_rna_seq.qmd
            - qmd/internal/analysis_atac_chip_seq.qmd
            - text: "Additional Analyses"
              href: "https://github.com/ty-troutman/Genomics-analyses"

        - section: "NGS Libraries"
          contents:
            - qmd/internal/Database_Barcodes.qmd
            - qmd/internal/Pooling_Submission.qmd

        - section: "Logs and Protocols"
          contents:
            - text: "Troutman-Lab-Share"
              href: "https://cchmc-my.sharepoint.com/:f:/r/personal/ty_troutman_cchmc_org/Documents/05_resources/Troutman-Lab-Share?csf=1&web=1&e=4Rn9Ve"
            - text: "Logs"
              href: "https://cchmc-my.sharepoint.com/:f:/r/personal/ty_troutman_cchmc_org/Documents/05_resources/Troutman-Lab-Share/logs_organization?csf=1&web=1&e=S6T1hq"
            - text: "Cell Preparation"
              href: "https://cchmc-my.sharepoint.com/:f:/r/personal/ty_troutman_cchmc_org/Documents/05_resources/Troutman-Lab-Share/protocols_methods/primary_cells?csf=1&web=1&e=U1fCwF"
            - text: "Equipment"
              href: "https://cchmc-my.sharepoint.com/:f:/r/personal/ty_troutman_cchmc_org/Documents/05_resources/Troutman-Lab-Share/equipment_manuals?csf=1&web=1&e=xe8rd3"
            - text: "Genomics"
              href: "https://cchmc-my.sharepoint.com/:f:/r/personal/ty_troutman_cchmc_org/Documents/05_resources/Troutman-Lab-Share/protocols_methods/genomics?csf=1&web=1&e=ZYrkdu"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual