---
title: "Pooling and Submission of Sequencing Libraries"
editor: source
format:
  html:
    toc: true
    toc-expand: 3
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
---

-   Only pool samples for sequencing that have compatible i5/p5 and i7/p7 barcodes. More information on Troutman lab barcode collisions can be found [here](https://github.com/ty-troutman/labSequencingBarcodes).
-   Don't unknowingly pool samples that have very different molecular weights.
-   Typically we target 15-25 million reads per sample for ATAC-seq, ChIP-seq and RNA-seq.
-   Samples profiling allelic biases (F1 hybrids) may require 50-100 million reads per sample.
-   Follow the instructions in the pooling calculator generated by the [BadDNA research group](https://baddna.uga.edu/tools-library_pooling_calculator.html) at the University of Georgia.
-   Example pooling sheet (coming soon).
-   Pooling requires an estimate of each sample's molecular weight and a qubit quantification of each samples concentration in ng/µl.

::: callout-important
## Critical!! Know which index orientation to submit.

Verify the appropriate orientation of the index sequence matches the requirements of the targeted sequencing platform. This must be appropriately entered in the submission sample sheet or demultiplexing will fail. Illumina NovaSeq v1.0 and v1.5 workflows utilize different strategies and require entering i5 index sequences appropriately. Forward strand i5 workflow is performed with v1.0 reagent kits, while reverse complement i5 workflow is performed with v1.5 reagent kits (NovaSeq). For the Illumina MiniSeq or NextSeq platforms, enter the i5 index as the reverse complement. When in doubt, verify with the core facility or sequencing provider and/or read the user manual!!
:::

# CCHMC Sequencing

The local [CCHMC Genomics Sequencing Facility](https://centerlink.cchmc.org/research/research---tabs/dna-sequencing-core) is currently directed by Hassan Chaib, PhD, and managed by David Fletcher and direct.

-   Non-core generated libraries can only be sequenced on a complete purchased flow cells.
-   One lane of a NovaSeq X Plus 1-B flow cell configured at PE50 is \$1,204.75, per [DNA Core Price Calculator](https://centerlink.cchmc.org/research/research---tabs/dna-sequencing-core/price-calculator).
-   More information on submission can be found at the bottom of this [page](https://dna.cchmc.org/www/nextgen_main.php).

## Core sequencing options:

```
Instrument       Type                        Flow Cell Type    Number Lanes Flow Cell  Total Cycles     Expected Output (M Clusters Lane)   Expected Output (M Clusters Total)
---------------  --------------------------  ---------------  -----------------------  --------------  ----------------------------------  -----------------------------------
iSeq 100         Reverse Complement          i1                                     1  300                                              4                                    4
MiSeq            Forward                     MiSeq                                  1  300, 500, 600                                   15                                   15
NovaSeq 6000     Reverse Complement (v1.5)   SP (S prime)                           1  100, 300, 500                                  720                                  720
NovaSeq 6000     Reverse Complement (v1.5)   S2                                     2  100, 200                                       720                                 1440
NovaSeq 6000     Reverse Complement (v1.5)   S4                                     2  100, 200, 300                                 1600                                 3200
NovaSeq 6000     Reverse Complement (v1.5)   S4                                     4  200, 300                                      2000                                 8000
NovaSeq X Plus   Reverse Complement          1.5B                                   2  100, 200, 300                                  720                                 1440
NovaSeq X Plus   Reverse Complement          10B                                    8  100, 200, 300                                 1200                                 9600
NovaSeq X Plus   Reverse Complement          25B                                    8  300                                           3000                                24000
```

## Lane submission requirements:

```         
Service              Input.Material                      Recommended.volume..µl.  Diluent          Minimum.Concentration 
-------------------  ---------------------------------  ------------------------  ---------------  ----------------------
iSeq 100             Illumina-compatible library pool                         30  10 mM Tris-HCl   5 nM                  
MiSeq                Illumina-compatible library pool                         30  10 mM Tris-HCl   5 nM                  
NovaSeq SP, S1, S2   Illumina-compatible library pool                         40  10 mM Tris-HCl   5 nM                  
NovaSeq S4           Illumina-compatible library pool                         80  10 mM Tris-HCl   5 nM                  
NovaSeqX 1.5B, 10B   Illumina-compatible library pool                         30  10 mM Tris-HCl   5 nM                  
NovaSeqX 25B         Illumina-compatible library pool                         60  10 mM Tris-HCl   5 nM                  

```

## [CCMHC Submission Sample Sheet](https://docs.google.com/spreadsheets/d/1jsq9Pe1AbLTcPkmoBw3DCj2ewyRkCqlng8q2KOK_6iQ/edit?usp=sharing):

Use the lab standardized naming convention!
