---
title: "Lab Members"
sidebar: false
---

### Ty D. Troutman, PhD

My research broadly focuses on innate immunity and the contribution of inflammation to acute and chronic disease. My specific research goals are to define the molecular mechanisms controlling the functions of macrophages and myeloid cells during illness. In my lab, we often apply diverse genomics technologies to purified tissue cells. With this strategy, we aim to decode transcriptional changes observed during disease by identifying the responsible transcription factors, upstream signaling pathways and sender cell populations. 

I have used this strategy successfully to 1) identify a hierarchical framework controlling niche specification of macrophages, 2) discover transcriptional mechanisms controlling functional diversification of macrophages during nonalcoholic steatohepatitis, and 3) predict *cis* and *trans*-acting factors promoting response differences from genetically diverse individuals. This framework requires the tool kit of a cellular immunologist, a molecular biologist and a computational biologist.

I've been a researcher for over 17 years and started working at Cincinnati Children's in 2021. Throughout my career, I have been fortunate to receive support from many scientific mentors. At the University of Texas (UT) at San Antonio, I was trained by Drs. Bernard Arulanandam and M. Neal Guenztel, while studying the immunological regulation of *Vibrio cholerae* pathogenesis. This experience established my desire for a career in science. I performed doctoral research under Dr. Chandrashekhar Pasare at UT Southwestern, defining new signaling mechanisms through the Toll-like receptor/interleukin one receptor (TLR/IL1R) superfamily. Finally, I trained with Dr. Christopher K. Glass at the University of California San Diego on gene regulation of macrophages during development and disease. These experiences have honed my value of scientific rigor and research mentorship, which I now use in my lab at Cincinnati Children's.

# Current members

### Steven Justiniano, PhD

### Justin Marlman, BS

# Past members
